### ISSUE TITLE
Add case studies

### ISSUE THREAD

**Issue by elizabethraley** [agilegovleaders/handbook#3]
Let's get a case study to demonstrate how this translates to government.

**Comment by pharten** [comment]
elizabethraley, I agree that we should get a case study to demonstrate how Agile Development translates to government projects.  There must be a government project currently underway implemented by software contractors that are using Agile methods.   if possible, get in on this conversation.

**Comment by pharten** [comment]
elizabethraley, I agree that we should get a case study to demonstrate how Agile Development translates to government projects. There must be government projects currently underway implemented by software contractors that are using Agile methods. if possible, please add to this conversation.

**Comment by elizabethraley** [comment]
pharten, thanks! We are actually working on a few now and have found some interesting information that we can't wait to share.

**Comment by lukefretwell** [comment]
@pharten we did it!

Added to the handbook, but you can also find them fresh off the presses here:

http://www.agilegovleaders.org/case-studies/

**Comment by pharten** [comment]
Congratulations @elizabethraley , @lukefretwell , and all others involved.
